name: Atualizacao Diaria NBA

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  rodar-pipeline:
    runs-on: windows-latest # <--- O TRUQUE ESTÁ AQUI

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar o ETL Diário
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main.py